stages:
   - build
   - test
   - quality
   - documentation

buildTests:
   stage: build
   script:
      - make test_project
   artifacts:
      paths:
         - test_project

test:
   stage: test
   script:
      - test_project

staticAnalysis:
   stage: quality
   script:
      - make static

style:
   stage: quality
   script:
      - make style

coverage:
   stage: quality
   script:
      - make coverage
   artifacts:
     paths:
        - coverage
   expire_in: 14 days

memoryLeaks:
   stage: quality
   script:
      - make memcheck
   artifacts:
      paths:
         - memcheck.xml
      expire_in: 14 days

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 14 days
